name: PerfBooster
options:
  bundleIdPrefix: com.arihulea26.perfbooster
targets:
  PerfBooster:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources]
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.arihulea26.perfbooster
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        DEVELOPMENT_TEAM: ""
        TARGETED_DEVICE_FAMILY: "1,2"
